server:
  port: 8104
  servlet:
    context-path: /student

spring:
  main:
    allow-circular-references: true
  application:
    name: CMS-Student-Service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/cms_student
    username: root
    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true



location:
  uri:
    baseUrl: http://localhost:8105
    getLocationById: /tuition/api/v1/tuition/##LOCATION-ID##

security:
  key: accessKey

logging:
  level:
    com.cms.student: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:./log}
