server:
  port: 8104
  servlet:
    context-path: /student

spring:
  application:
    name: CMS-Student-Service

  datasource:
    url: jdbc:mysql://b07da724040dd7:94fcc9f7@us-cdbr-east-06.cleardb.net/heroku_1e995eee500727d?reconnect=true
#    username: root
#    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
  instance:
    preferIpAddress: true



location:
  uri:
#    baseUrl: http://localhost:8105
    baseUrl: https://cms-location.herokuapp.com
    getLocationById: /tuition/api/v1/tuition/##LOCATION-ID##

security:
  key: accessKey